poetry + tmdb_api
spprashant/movie-butler pull request #13
Opened 2022-11-06 21:30 UTC by spprashant

- Added poetry integration for dependency management and build help
- Started TMDB api integration for data load pipeline

2022-11-06 23:31 UTC, putstrln requested changes

2022-11-06 23:31 UTC, putstrln commented on server/src/core/tmdb_api.py
> +class TmdbAPI:
let's keep names generic for easy refactoring later, TmdbAPI to SomeFunctionAPI or something.
same goes for var names

2022-11-16 03:28 UTC, JDPelayoPetit approved these changes

2022-11-16 22:54 UTC, putstrln approved these changes

2022-11-17 03:20 UTC, merged